"""Materials-science-style synthetic marker charts -> labels.jsonl
(docs/design/local-model.md, データ: 合成).

Fills what PlotQA dot_line lacks: numeric x (T = 300-900 K, 1000/T,
composition, log x), log y and log10-printed y, open/filled markers of
several shapes, error bars, 1-8 series, legends inside the plot, dense and
overlapping markers, line+marker, occasional insets, varied fonts/sizes/dpi,
and JPEG artefacts.

Every marker centre is reported from matplotlib itself: data -> display
through ax.transData after the figure is drawn, then display -> image pixels.
The figure is drawn SS times larger and shrunk, because Agg puts markers on
the integer pixel grid; the shrunk marker sits within ~0.2 px of its label
(tests/scripts/test_gen_synth_materials.py measures the ink centroids).
Tick (px, value) pairs come from the drawn major ticks, the value parsed
from the printed label text. Points hidden under an opaque legend or an
inset are dropped from the label (they are not visible). Insets carry
lines only, never markers, so every visible marker is labelled.

Each image i is drawn from numpy's default_rng(SEED + i): any image can be
regenerated alone. Images are written by a process pool, labels gathered in
order. Data are generated (no real figures, no model outputs).

Usage:
  .venv/bin/python scripts/train/gen_synth_materials.py --n 20000 [--out DIR] [--workers 24]
"""

from __future__ import annotations

import argparse
import io
import json
import math
import sys
from multiprocessing import Pool
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from matplotlib import colors as mcolors  # noqa: E402
from PIL import Image  # noqa: E402

from real_chart_bench.adapter.synth_chart_labels import (  # noqa: E402
    display_to_image,
    inside_any,
    marker_class,
    parse_tick_text,
)
from real_chart_bench.domain.training_data import (  # noqa: E402
    max_axis_residual_px,
    validate_label,
)

SEED = 20261006
SOURCE = "synth-materials"
LICENSE = "CC-BY-4.0"  # generated by this project's code from random data (owner, 2026-10-06)
OUT = Path.home() / ".cache" / "real-chart-bench" / "train-data" / "synth-materials"
MAX_RESIDUAL_PX = 1.0
# Agg places every marker on the integer pixel grid. Drawing SS times larger
# and shrinking (box filter) puts a marker within ~0.2 px of its data point.
SS = 4

MARKERS = ["o", "s", "^", "v", "D", "d", "<", ">", "x", "+", "*", "p", "h"]
# circles, squares and triangles dominate materials figures
MARKER_P = [.20, .14, .12, .08, .10, .03, .04, .04, .05, .05, .05, .05, .05]
FONTS = ["DejaVu Sans", "DejaVu Serif", "Liberation Sans", "Liberation Serif",
         "Nimbus Roman", "Nimbus Sans", "C059"]  # all carry U+2212 (minus)
PALETTES = ["tab10", "Set1", "Dark2", "viridis", "plasma", "coolwarm", "black", "gray"]
LEGEND_LOCS = ["best", "upper left", "upper right", "lower left", "lower right",
               "center left", "center right", "upper center", "lower center"]


# --------------------------------------------------------------------- data
def x_spec(rng):
    """(kind, label, scale, lo, hi): how the x axis is printed."""
    kind = rng.choice(["T", "invT", "comp", "linear", "logx"], p=[0.35, 0.2, 0.15, 0.2, 0.1])
    if kind == "T":
        lo = float(rng.choice([250, 300, 300, 350, 400]))
        hi = float(rng.choice([600, 700, 800, 900, 1000]))
        return kind, rng.choice(["T (K)", "Temperature (K)", "$T$ (K)", "T [K]"]), "linear", lo, hi
    if kind == "invT":
        lo, hi = 1000 / 900, 1000 / 300
        return kind, rng.choice(["1000/T (K$^{-1}$)", "$1000/T$ (1/K)", "1000/T"]), "linear", lo, hi
    if kind == "comp":
        hi = float(rng.choice([0.1, 0.2, 0.5, 1.0]))
        names = ["x", "Composition x", "$x$ in A$_{1-x}$B$_x$", "Content (at.%)"]
        return kind, rng.choice(names), "linear", 0.0, hi
    if kind == "logx":
        a = int(rng.integers(-3, 3))
        return kind, rng.choice(["Frequency (Hz)", "Carrier conc. (cm$^{-3}$)", "t (s)"]), \
            "log", 10.0**a, 10.0 ** (a + int(rng.integers(2, 6)))
    lo = float(rng.uniform(-50, 50))
    return kind, rng.choice(["Pressure (GPa)", "Field (T)", "Strain (%)", "E (eV)"]), "linear", \
        lo, lo + float(rng.choice([1, 2, 5, 10, 20, 50, 100]))


def y_spec(rng):
    """(mode, label): 'linear', 'log' (log axis), or 'log10' (log10 printed)."""
    mode = rng.choice(["linear", "log", "log10"], p=[0.5, 0.3, 0.2])
    labels = {
        "linear": ["S ($\\mu$V/K)", "zT", "$\\kappa$ (W/mK)", "PF (mW/mK$^2$)", "Intensity (a.u.)"],
        "log": ["$\\sigma$ (S/cm)", "$\\rho$ ($\\Omega$ cm)", "n (cm$^{-3}$)", "D (cm$^2$/s)"],
        "log10": ["log $\\sigma$ (S/cm)", "log$_{10}$ $\\rho$", "ln($\\sigma T$)", "log D"],
    }
    return mode, rng.choice(labels[mode])


def curve(rng, t):
    """A smooth curve on t in [0, 1] (one of a few materials-like shapes)."""
    shape = rng.choice(["line", "power", "peak", "sigmoid", "exp", "wiggle"])
    if shape == "line":
        return rng.normal() * t
    if shape == "power":
        return np.sign(rng.normal()) * t ** rng.uniform(0.3, 3)
    if shape == "peak":
        c, w = rng.uniform(0.2, 0.9), rng.uniform(0.1, 0.5)
        return np.exp(-((t - c) / w) ** 2)
    if shape == "sigmoid":
        return 1 / (1 + np.exp(-(t - rng.uniform(0.2, 0.8)) * rng.uniform(5, 25)))
    if shape == "exp":
        return np.exp(rng.uniform(-3, 3) * t)
    k = rng.integers(1, 4)
    return np.sin(2 * math.pi * k * t + rng.uniform(0, 6)) * rng.uniform(0.2, 1) + rng.normal() * t


def series_data(rng, n_series, xs_lo, xs_hi, x_scale, y_mode, dense):
    """Per series (x_print, y_print) in printed space."""
    y_lo = float(rng.uniform(-6, 2)) if y_mode != "linear" else float(rng.uniform(-100, 100))
    span = float(rng.uniform(1, 6)) if y_mode != "linear" else float(10 ** rng.uniform(-1, 3))
    shared_x = rng.random() < 0.6
    n_pts = int(rng.integers(25, 80)) if dense else int(rng.integers(3, 20))
    base_t = np.sort(rng.uniform(0, 1, n_pts)) if rng.random() < 0.4 else np.linspace(0, 1, n_pts)
    out = []
    for _ in range(n_series):
        t = base_t if shared_x else np.sort(rng.uniform(0, 1, int(rng.integers(3, n_pts + 1))))
        if x_scale == "log":
            x = 10 ** (math.log10(xs_lo) + t * (math.log10(xs_hi) - math.log10(xs_lo)))
        else:
            x = xs_lo + t * (xs_hi - xs_lo)
        c = curve(rng, t)
        c = (c - c.min()) / (np.ptp(c) or 1.0)
        level = rng.uniform(0, 0.6)
        amp = rng.uniform(0.2, 1.0) * (1 - level)
        noise = rng.normal(0, rng.uniform(0, 0.04), len(t))
        y = y_lo + span * np.clip(level + amp * c + noise, -0.1, 1.1)
        if y_mode == "log":
            y = 10.0**y  # stored as values; plotted on a log axis
        out.append((x, y))
    return out


# ------------------------------------------------------------------- render
def colours(rng, n):
    pal = rng.choice(PALETTES)
    if pal == "black":
        return ["#000000"] * n
    if pal == "gray":
        return [mcolors.to_hex((g, g, g)) for g in np.linspace(0, 0.6, n)]
    cmap = plt.get_cmap(pal)
    if pal in ("tab10", "Set1", "Dark2"):
        return [mcolors.to_hex(cmap(i % cmap.N)) for i in range(n)]
    return [mcolors.to_hex(cmap(v)) for v in np.linspace(0.05, 0.9, n)]


def axis_ticks(ax, which, height, scale):
    """Major ticks inside the view: (image px, printed value)."""
    axis = ax.xaxis if which == "x" else ax.yaxis
    lo, hi = sorted(ax.get_xlim() if which == "x" else ax.get_ylim())
    ticks = []
    # a log axis spanning under a decade labels its minor ticks (2x10^-1, ...)
    candidates = axis.get_major_ticks()
    if axis.get_scale() == "log":
        candidates = candidates + axis.get_minor_ticks()
    for tick in candidates:
        loc = tick.get_loc()
        text = tick.label1.get_text() if tick.label1.get_visible() else ""
        value = parse_tick_text(text)
        if value is None or not (lo - 1e-12 * abs(lo) <= loc <= hi + 1e-12 * abs(hi)):
            continue
        if not math.isclose(value, loc, rel_tol=1e-6, abs_tol=1e-9 * max(1.0, abs(hi - lo))):
            continue  # printed text is not the tick's value (offset/multiplier): skip
        pt = (loc, ax.get_ylim()[0]) if which == "x" else (ax.get_xlim()[0], loc)
        dx, dy = ax.transData.transform(pt)
        px = display_to_image(dx, dy, height=height, scale=scale)[0 if which == "x" else 1]
        ticks.append({"px": round(float(px), 3), "value": float(value)})
    return ticks


def bbox_image(bb, height, scale):
    x0, y0 = display_to_image(bb.x0, bb.y1, height=height, scale=scale)
    x1, y1 = display_to_image(bb.x1, bb.y0, height=height, scale=scale)
    return (float(x0), float(y0), float(x1), float(y1))


def render(i: int, force: dict | None = None):
    """Draw image i. `force` pins some random choices (style, errorbars, grid,
    inset) after they are drawn, so the rest of image i is unchanged; the
    tests use it to get isolated plain markers."""
    force = force or {}
    rng = np.random.default_rng(SEED + i)
    font = str(rng.choice(FONTS))
    fs = float(rng.uniform(6, 14))
    rc = {
        "font.family": font, "font.size": fs, "mathtext.fontset": "dejavusans",
        "axes.linewidth": float(rng.uniform(0.5, 2.0)),
        "xtick.direction": str(rng.choice(["in", "out"])),
        "ytick.direction": str(rng.choice(["in", "out"])),
        "xtick.top": bool(rng.random() < 0.5), "ytick.right": bool(rng.random() < 0.5),
        "xtick.minor.visible": bool(rng.random() < 0.4),
        "ytick.minor.visible": bool(rng.random() < 0.4),
        "axes.formatter.useoffset": False,
        "axes.formatter.limits": (-5, 6),
    }
    dpi = int(rng.choice([72, 96, 100, 120, 150, 200]))
    w_in = float(rng.uniform(3.0, 6.5))
    h_in = float(w_in * rng.uniform(0.6, 1.0))
    while w_in * dpi > 1280 or h_in * dpi > 1024:
        dpi = int(dpi * 0.8)
    W, H = round(w_in * dpi), round(h_in * dpi)  # the image size
    w_in, h_in = W / dpi, H / dpi

    xkind, xlabel, x_scale, x_lo, x_hi = x_spec(rng)
    y_mode, ylabel = y_spec(rng)
    n_series = int(rng.choice([1, 2, 3, 4, 5, 6, 7, 8], p=[.14, .2, .2, .16, .12, .08, .05, .05]))
    dense = rng.random() < 0.15
    data = series_data(rng, n_series, x_lo, x_hi, x_scale, y_mode, dense)
    cols = colours(rng, n_series)
    same_marker = rng.random() < 0.15
    mk_order = list(rng.choice(MARKERS, size=len(MARKERS), replace=False, p=MARKER_P))
    style = rng.choice(["markers", "line+markers", "dashed+markers"], p=[0.45, 0.4, 0.15])
    style = force.get("style", style)
    errbars = force.get("errorbars", rng.random() < 0.2)
    open_mode = rng.choice(["filled", "open", "mixed"], p=[0.45, 0.3, 0.25])
    ms = float(rng.uniform(3, 11)) * (0.6 if dense else 1.0)

    with plt.rc_context(rc):
        fig = plt.figure(figsize=(w_in, h_in), dpi=dpi * SS)
        ax = fig.add_subplot(111)
        if x_scale == "log":
            ax.set_xscale("log")
        if y_mode == "log":
            ax.set_yscale("log")
        series_meta = []
        for s, (x, y) in enumerate(data):
            mk = mk_order[0] if same_marker else mk_order[s % len(mk_order)]
            filled = {"filled": True, "open": False, "mixed": bool(s % 2 == 0)}[open_mode]
            if mk in ("x", "+"):
                filled = None  # line markers have no face
            ls = {"markers": "none", "line+markers": "-", "dashed+markers": "--"}[style]
            kw = dict(marker=mk, markersize=ms, linestyle=ls, color=cols[s],
                      linewidth=float(rng.uniform(0.6, 1.8)),
                      markeredgewidth=float(rng.uniform(0.6, 1.6)),
                      label=f"{rng.choice(['x', 'y', 'n', 'S'])} = {rng.uniform(0, 1):.2f}"
                      if rng.random() < 0.7 else f"Sample {chr(65 + s)}")
            if filled is False:
                kw["markerfacecolor"] = "none" if rng.random() < 0.7 else "white"
            if errbars:
                err = np.abs(y) * rng.uniform(0.02, 0.15) if y_mode == "log" else \
                    np.full(len(y), np.ptp(y) * rng.uniform(0.02, 0.1) + 1e-9)
                if y_mode == "log":
                    err = np.minimum(err, 0.9 * y)
                ax.errorbar(x, y, yerr=err, capsize=float(rng.uniform(0, 4)), **kw)
            else:
                ax.plot(x, y, **kw)
            series_meta.append((kw["label"], mk, filled, cols[s], x, y))

        # view limits: all data inside, with margins
        ax.margins(x=float(rng.uniform(0.03, 0.12)), y=float(rng.uniform(0.05, 0.2)))
        ax.autoscale_view()
        if xkind == "T" and rng.random() < 0.5:
            ax.set_xlim(x_lo - (x_hi - x_lo) * 0.05, x_hi + (x_hi - x_lo) * 0.05)
        ax.set_xlabel(xlabel)
        ax.set_ylabel(ylabel)
        grid = force.get("grid", rng.random() < 0.15)
        if grid:
            ax.grid(True, alpha=float(rng.uniform(0.2, 0.6)),
                    linestyle=str(rng.choice(["-", ":", "--"])))

        legend = None
        if n_series > 1 or rng.random() < 0.3:
            legend = ax.legend(loc=str(rng.choice(LEGEND_LOCS)), frameon=bool(rng.random() < 0.6),
                               fontsize=fs * float(rng.uniform(0.6, 1.0)),
                               ncol=int(rng.choice([1, 1, 1, 2])))
        inset = None
        if force.get("inset", rng.random() < 0.08):
            corner = [[0.6, 0.6], [0.08, 0.6], [0.6, 0.12], [0.08, 0.12]][int(rng.integers(4))]
            inset = ax.inset_axes([corner[0], corner[1], 0.32, 0.3])
            tt = np.linspace(0, 1, 50)
            inset.plot(tt, curve(rng, tt), color="k", lw=1)
            inset.tick_params(labelsize=fs * 0.6)

        fig.tight_layout(pad=float(rng.uniform(0.2, 1.2)))
        fig.canvas.draw()
        Wh, Hh = fig.canvas.get_width_height()
        assert (Wh, Hh) == (W * SS, H * SS), (Wh, Hh, W, H)

        hide = []
        legend_bbox = None
        if legend is not None:
            legend_bbox = bbox_image(legend.get_window_extent(), Hh, SS)
            if legend.get_frame_on():  # an opaque frame hides the points under it
                hide.append(legend_bbox)
        if inset is not None:
            # only the inset's own (white) axes area hides points; its tick
            # labels outside it are drawn over the data without a background
            hide.append(bbox_image(inset.get_window_extent(), Hh, SS))

        x_ticks = axis_ticks(ax, "x", Hh, SS)
        y_ticks = axis_ticks(ax, "y", Hh, SS)
        series = []
        n_hidden = 0
        for label, mk, filled, col, x, y in series_meta:
            disp = ax.transData.transform(np.column_stack([x, y]))
            pts_px, pts_val = [], []
            for (dx, dy), xv, yv in zip(disp, x, y, strict=True):
                px, py = display_to_image(float(dx), float(dy), height=Hh, scale=SS)
                if inside_any((px, py), hide):
                    n_hidden += 1
                    continue
                pts_px.append([round(px, 3), round(py, 3)])
                pts_val.append([float(xv), float(yv)])
            if pts_px:
                series.append({"label": label, "marker": marker_class(mk), "filled": filled,
                               "color": col, "points_px": pts_px, "points_value": pts_val,
                               "mpl_marker": mk})
        pb = bbox_image(ax.get_window_extent(), Hh, SS)

        jpeg = rng.random() < 0.5
        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=dpi * SS)
        plt.close(fig)

    img = Image.open(io.BytesIO(buf.getvalue())).convert("RGB")
    assert img.size == (W * SS, H * SS), (img.size, W, H)
    img = img.resize((W, H), Image.BOX)
    name = f"{i:06d}.jpg" if jpeg else f"{i:06d}.png"
    quality = int(rng.integers(35, 92)) if jpeg else None

    axes = None
    if len(x_ticks) >= 2 and len(y_ticks) >= 2:
        axes = {"x": {"scale": x_scale, "ticks": x_ticks},
                "y": {"scale": "log" if y_mode == "log" else "linear", "ticks": y_ticks}}
    label = {
        "image": f"images/{name}", "width": W, "height": H,
        "source": SOURCE, "license": LICENSE, "paper_id": None,
        "axes": axes, "plot_bbox": [round(v, 3) for v in pb], "series": series,
        "synth": {"seed": SEED + i, "x_kind": xkind, "y_mode": y_mode, "dpi": dpi, "font": font,
                  "jpeg_quality": quality, "dense": bool(dense), "errorbars": bool(errbars),
                  "inset": inset is not None, "style": str(style), "n_hidden": n_hidden,
                  "marker_size_px": round(ms * dpi / 72, 2), "grid": bool(grid),
                  "legend_bbox": [round(v, 3) for v in legend_bbox] if legend_bbox else None,
                  "legend_frame": bool(legend is not None and legend.get_frame_on())},
    }
    return i, label, img, quality


def write_one(args):
    i, out = args
    i, label, img, quality = render(i)
    errors = validate_label(label)
    r = max_axis_residual_px(label)
    if errors or not label["series"] or (r is not None and r > MAX_RESIDUAL_PX):
        return i, None, f"errors={errors[:2]} residual={r}"
    path = out / label["image"]
    if quality:
        img.save(path, "JPEG", quality=quality)
    else:
        img.save(path, "PNG", optimize=True)
    return i, label, None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=20000)
    ap.add_argument("--start", type=int, default=0)
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--workers", type=int, default=24)
    args = ap.parse_args()
    (args.out / "images").mkdir(parents=True, exist_ok=True)
    labels, skipped = [], {}
    jobs = [(i, args.out) for i in range(args.start, args.start + args.n)]
    with Pool(args.workers) as pool:
        for k, (i, label, why) in enumerate(pool.imap(write_one, jobs, chunksize=16)):
            if label is None:
                skipped[i] = why
            else:
                labels.append(label)
            if (k + 1) % 1000 == 0:
                print(f"{k + 1}/{args.n} done, {len(skipped)} skipped", flush=True)
    with (args.out / "labels.jsonl").open("w") as f:
        for lab in labels:
            f.write(json.dumps(lab, ensure_ascii=False) + "\n")
    (args.out / "skipped.json").write_text(json.dumps(skipped, indent=1))
    (args.out / "LICENSE").write_text(
        "Synthetic charts generated by real-chart-bench scripts/train/gen_synth_materials.py\n"
        "from random data. Licensed under CC BY 4.0\n"
        "(https://creativecommons.org/licenses/by/4.0/).\n"
        "Attribution: real-chart-bench (https://github.com/t29mato/real-chart-bench).\n")
    size = sum(p.stat().st_size for p in args.out.rglob("*") if p.is_file())
    print(f"wrote {len(labels)} labels, skipped {len(skipped)}, {size} bytes", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
