"""Synthetic stress TRAINING set for MarkerNet v2 (docs/design/local-model.md,
方式A v2, データ: synth-stress).

The same kind of images as the detector's stress validation set
(marker_detector/gen_stress_val.py): large markers (1.5-2.5x), half-filled,
cut into quarters by a white cross, a same-colour cross drawn inside, and
2-3x dpi renders. The `force` choices come from gen_stress_val.stress_for
(imported, called with an offset so they differ from the validation set's);
images are drawn by gen_synth_materials.render.

Seeds: image index 6,000,000 + j, i.e. numpy seed SEED + 6,000,000 + j. The
validation set uses index 5,000,000+ and the base set 0-19,999: no overlap.

Output (outside the repo): ~/.cache/real-chart-bench/train-data/synth-stress/
  images/, labels.jsonl, LICENSE; manifest data/train_manifest/synth-stress.json

  .venv/bin/python scripts/train/gen_synth_stress.py [--n 4000] [--workers 8]
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from multiprocessing import Pool
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts/train"))
sys.path.insert(0, str(REPO / "scripts/train/marker_detector"))
sys.path.insert(0, str(REPO / "src"))

import gen_stress_val  # noqa: E402
import gen_synth_materials as gen  # noqa: E402

from real_chart_bench.domain.training_data import (  # noqa: E402
    max_axis_residual_px,
    validate_label,
)

OUT = Path.home() / ".cache/real-chart-bench/train-data/synth-stress"
MANIFEST = REPO / "data/train_manifest/synth-stress.json"
FIRST = 6_000_000
FORCE_OFFSET = 1_000_000  # stress_for seeds 1,777,000+j: not the validation set's 777,000+j
SOURCE = "synth-stress"
MAX_RESIDUAL_PX = 1.0


def write_one(j: int):
    force = gen_stress_val.stress_for(FORCE_OFFSET + j)
    _, label, img, quality = gen.render(FIRST + j, force=force)
    label["source"] = SOURCE
    label["synth"]["stress"] = force
    r = max_axis_residual_px(label)
    if validate_label(label) or not label["series"] or (r is not None and r > MAX_RESIDUAL_PX):
        return j, None
    path = OUT / label["image"]
    if quality:
        img.save(path, "JPEG", quality=quality)
    else:
        img.save(path, "PNG", optimize=True)
    return j, label


def manifest(labels: list[dict], skipped: int, requested: int) -> dict:
    stress = [lab["synth"]["stress"] for lab in labels]
    scales = Counter(str((lab["axes"]["x"]["scale"], lab["axes"]["y"]["scale"]))
                     if lab["axes"] else "None" for lab in labels)
    return {
        "source": SOURCE, "path": "~/.cache/real-chart-bench/train-data/synth-stress/",
        "license": "CC-BY-4.0",
        "attribution": "generated by real-chart-bench from random data",
        "made_by": "scripts/train/gen_synth_stress.py",
        "params": {"seed": f"numpy default_rng({gen.SEED} + {FIRST} + j)",
                   "force": f"gen_stress_val.stress_for({FORCE_OFFSET} + j)",
                   "supersampling": gen.SS, "max_residual_px": MAX_RESIDUAL_PX,
                   "n_requested": requested, "skipped": skipped},
        "disk_bytes": sum(p.stat().st_size for p in OUT.rglob("*") if p.is_file()),
        "label_files": {"labels.jsonl": {
            "split": "train", "images": len(labels),
            "points": sum(len(s["points_px"]) for lab in labels for s in lab["series"]),
            "axes_known": sum(lab["axes"] is not None for lab in labels),
            "axis_scales_xy": dict(scales),
            "stress": {
                "overlay": dict(Counter(str(s.get("overlay")) for s in stress)),
                "white_cross": sum(s.get("overlay_color") == "white" for s in stress),
                "fillstyle": dict(Counter(str(s.get("fillstyle")) for s in stress)),
                "high_dpi": sum("dpi_scale" in s for s in stress),
            },
        }},
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=4000)
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args()
    (OUT / "images").mkdir(parents=True, exist_ok=True)
    labels, skipped = [], 0
    # a few extra indices cover the rare skipped image; the first n valid are kept
    jobs = range(args.n + max(50, args.n // 20))
    with Pool(args.workers) as pool:
        for j, lab in pool.imap(write_one, jobs, chunksize=8):
            if lab is None:
                skipped += 1
            elif len(labels) < args.n:
                labels.append(lab)
            else:
                (OUT / lab["image"]).unlink()  # surplus
            if (j + 1) % 500 == 0:
                print(f"{j + 1} done, {len(labels)} kept, {skipped} skipped", flush=True)
    with (OUT / "labels.jsonl").open("w") as f:
        for lab in labels:
            f.write(json.dumps(lab, ensure_ascii=False) + "\n")
    (OUT / "LICENSE").write_text(
        "Synthetic charts generated by real-chart-bench scripts/train/gen_synth_stress.py\n"
        "from random data. Licensed under CC BY 4.0\n"
        "(https://creativecommons.org/licenses/by/4.0/).\n"
        "Attribution: real-chart-bench (https://github.com/t29mato/real-chart-bench).\n")
    m = manifest(labels, skipped, args.n)
    MANIFEST.write_text(json.dumps(m, indent=1) + "\n")
    print(f"wrote {len(labels)} labels, skipped {skipped}, {m['disk_bytes']} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
