"""Summarise a training-data directory into data/train_manifest/<source>.json
(docs/design/local-model.md, データ: 合成). The data stay outside the repo;
the manifest records what is there, its licence and how it was made.

Usage:
  .venv/bin/python scripts/train/train_manifest.py plotqa
  .venv/bin/python scripts/train/train_manifest.py synth-materials
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

from real_chart_bench.domain.training_data import validate_label

REPO = Path(__file__).resolve().parents[2]
CACHE = Path.home() / ".cache" / "real-chart-bench" / "train-data"

META = {
    "plotqa": {
        "license": "CC-BY-4.0",
        "attribution": "Methani et al., PlotQA: Reasoning over Scientific Plots, WACV 2020; "
                       "https://github.com/NiteshMethani/PlotQA",
        "made_by": "scripts/train/prepare_plotqa.py",
        "params": {
            "plot_type": "dot_line", "splits": ["train", "val"], "test_split": "never used",
            "max_residual_px": 3.0,
            "points_px": "centre of each PlotQA marker bbox",
            "x_axis": "years at equal steps; axes null and x_categorical true when the "
                      "printed years are not evenly stepped (y ticks kept in y_ticks)",
        },
        "label_files": {"labels.jsonl": "train", "labels_val.jsonl": "val"},
    },
    "synth-materials": {
        "license": "CC-BY-4.0",
        "attribution": "generated by real-chart-bench from random data",
        "made_by": "scripts/train/gen_synth_materials.py",
        "params": {
            "seed": "numpy default_rng(20261006 + image index)",
            "supersampling": 4, "max_residual_px": 1.0,
            "n_requested": 20000,
        },
        "label_files": {"labels.jsonl": "train"},
    },
}


def summarise(source: str) -> dict:
    root = CACHE / source
    meta = META[source]
    files = {}
    for name, split in meta["label_files"].items():
        path = root / name
        if not path.exists():
            continue
        labels = [json.loads(line) for line in path.open()]
        bad = sum(bool(validate_label(lab)) for lab in labels)
        pts = sum(len(s["points_px"]) for lab in labels for s in lab["series"])
        n_series = Counter(len(lab["series"]) for lab in labels)
        markers = Counter((s["marker"], s["filled"]) for lab in labels for s in lab["series"])
        scales = Counter(
            (lab["axes"]["x"]["scale"], lab["axes"]["y"]["scale"]) if lab["axes"] else None
            for lab in labels
        )
        entry = {
            "split": split, "images": len(labels), "invalid_labels": bad, "points": pts,
            "series_per_image": dict(sorted(n_series.items())),
            "axes_known": sum(lab["axes"] is not None for lab in labels),
            "axis_scales_xy": {str(k): v for k, v in scales.most_common()},
            "marker_filled": {f"{m}/{f}": v for (m, f), v in markers.most_common()},
        }
        if source == "synth-materials":
            syn = [lab["synth"] for lab in labels]
            entry["synth"] = {
                k: dict(Counter(str(s[k]) for s in syn).most_common())
                for k in ("x_kind", "y_mode", "style", "errorbars", "dense", "inset", "dpi",
                          "font", "legend_frame")
            }
            entry["synth"]["jpeg"] = sum(s["jpeg_quality"] is not None for s in syn)
            entry["synth"]["points_hidden_dropped"] = sum(s["n_hidden"] for s in syn)
        files[name] = entry
    size = sum(p.stat().st_size for p in root.rglob("*") if p.is_file())
    return {
        "source": source,
        "path": f"~/.cache/real-chart-bench/train-data/{source}/",
        "license": meta["license"],
        "attribution": meta["attribution"],
        "made_by": meta["made_by"],
        "params": meta["params"],
        "disk_bytes": size,
        "label_files": files,
    }


def main() -> int:
    source = sys.argv[1]
    out = REPO / "data" / "train_manifest" / f"{source}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(summarise(source), indent=1, ensure_ascii=False) + "\n")
    print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
